version: '3.9'
services:
  db-product:
    image: postgres:alpine
    container_name: db-product
    hostname: db-product
    environment:
      - POSTGRES_USER=${DB_PRODUCT_USER}
      - POSTGRES_PASS=${DB_PRODUCT_PASS}
      - POSTGRES_DB=${DB_PRODUCT_NAME}
    ports:
      - "127.0.0.1:${DB_PRODUCT_PORT}:5432"
    restart: unless-stopped
    networks:
      - tokoku

  db-user:
    image: postgres:alpine
    container_name: db-user
    hostname: db-user
    environment:
      - POSTGRES_USER=${DB_USER_USER}
      - POSTGRES_PASS=${DB_USER_PASS}
      - POSTGRES_DB=${DB_USER_NAME}
    ports:
      - "127.0.0.1:${DB_USER_PORT}:5432"
    restart: unless-stopped
    networks:
      - tokoku
  
  db-order:
    image: postgres:alpine
    container_name: db-order
    hostname: db-order
    environment:
      - POSTGRES_USER=${DB_ORDER_USER}
      - POSTGRES_PASS=${DB_ORDER_PASS}
      - POSTGRES_DB=${DB_ORDER_NAME}
    ports:
      - "127.0.0.1:${DB_ORDER_PORT}:5432"
    restart: unless-stopped
    networks:
      - tokoku

  app-product:
    build:
      context: ./product/
      dockerfile: Dockerfile
      args:
        - EXPOSE_PORT=${APP_PRODUCT_PORT}
    env_file:
      - ./product/.env
    restart: unless-stopped
    ports:
      - ${APP_PRODUCT_PORT}:3000
    networks:
      - tokoku
    depends_on:
      - db-product
  
  app-order:
    build:
      context: ./order/
      dockerfile: Dockerfile
      args:
        - HTTP_PORT=${HTTP_ORDER_PORT}
        - GRPC_PORT=${GRPC_ORDER_PORT}
    env_file:
      - ./order/.env
    restart: unless-stopped
    ports:
      - ${HTTP_ORDER_PORT}:3000
      - ${GRPC_ORDER_PORT}:9000
    networks:
      - tokoku
    depends_on:
      - db-order

  app-user:
    build:
      context: ./user/
      dockerfile: Dockerfile
      args:
        - EXPOSE_PORT=${APP_USER_PORT}
    env_file:
      - ./user/.env
    restart: unless-stopped
    ports:
      - ${APP_USER_PORT}:3000
    networks:
      - tokoku
    depends_on:
      - db-user
  
  rabbitmq:
    image: rabbitmq:3.13.0-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    networks:
      - tokoku

networks:
  tokoku:
    driver: bridge