---
global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
- job_name: tokoku
  static_configs:
  - target: ["app-product:5000"]
  - target: ["app-order:6000"]
  - target: ["app-user:4000"]