name: build-binary
on: [push, pull_request]

jobs:
  build-binary-go:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: echo "running build binary"
    - uses: actions/setup-go@v5

      with:
        go-version: '1.21.6'


    - name: running unit test product services
      run: cd product && go mod tidy && go test -v ./test/

    - name: build binary order services
      run: cd order && go mod tidy && go build -o build/main -v api/api.go

    - name: build binary webhook services
      run: cd webhook && go mod tidy && go build -o build/main